// swift-tools-version:5.3
//  The swift-tools-version declares the minimum version of Swift required to build this package.
//
// --------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// --------------------------------------------------------------------------
import PackageDescription

let package = Package(
    name: "TrouterClientIos",
    platforms: [
        .macOS(.v10_14), .iOS(.v13), .tvOS(.v13)
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "TrouterClientIos",
            targets: ["TrouterClientIos"])
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .binaryTarget(
            name: "TrouterClientIos",
            url: "https://github.com/microsoft/trouter-client-ios/releases/download/v0.0.1-beta.1/TrouterClientIos-0.0.1-beta.1.zip",
            checksum: "f900d313cfe71856e94ca92cacf3c736e25c7483ef4756b72070a520f923d2bd"
        )
    ]
)
